### ISSUE TITLE
Addon crushing

### ISSUE THREAD

**Issue by SonOfFree** [nightflyer73/plugin.video.raitv#29] opened 2018-02-24 20:01 UTC
Hello, running Kodi 17.6 on Windows 10, add-on does not load. It used to work fine. This is the error I get from the log.

`20:57:19.193 T:9504   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 403: Forbidden
                                            Traceback (most recent call last):
                                              File "C:\Users\Dorigo-Hsu\AppData\Roaming\Kodi\addons\plugin.video.raitv\default.py", line 429, in <module>
                                                log_country()
                                              File "C:\Users\Dorigo-Hsu\AppData\Roaming\Kodi\addons\plugin.video.raitv\default.py", line 354, in log_country
                                                country = raiplay.getCountry()
                                              File "C:\Users\Dorigo-Hsu\AppData\Roaming\Kodi\addons\plugin.video.raitv\resources\lib\raiplay.py", line 16, in getCountry
                                                response = urllib2.urlopen(self.localizeUrl).read()
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 435, in open
                                                response = meth(req, response)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 548, in http_response
                                                'http', request, response, code, msg, hdrs)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 473, in error
                                                return self._call_chain(*args)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 407, in _call_chain
                                                result = func(*args)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 556, in http_error_default
                                                raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
                                            HTTPError: HTTP Error 403: Forbidden
                                            -->End of Python script error report<--`

**Comment by realtebo** [comment] 2018-02-24 21:33
confermo, stesso problema, su tutte le piattaforme

**Comment by nightflyer73** [comment] 2018-02-25 07:05
Duplicate of #26.

**Closed by nightflyer73** 2018-02-25 07:05 UTC
