### ISSUE TITLE
Rai ondemand addon disappeared

### ISSUE THREAD

**Issue by linoreale** [nightflyer73/plugin.video.raitv#41] opened 2018-10-17 06:29 UTC
Hi Nightfly,
thank you for your remarkable work.
Since a few days Rai Ondemand addon has disappeared from the Kodi 17 Krypton video addon.
I tried to install it using the zip file provided here but not all programmes are availlable, in fact you can see just Live programmes and not on demand videos.
I would love to use it again, could you help me please?
Thanks and regards

**Comment by nightflyer73** [comment] 2018-10-17 07:35
AFAIK ondemand programs work fine. Are you located abroad?

Anyway, if you have issues, please open a new bug and provide:

- Kodi verision used
- addon version used
- steps to reproduce the bug
- upload the log file to pastebin.com or similar service

Marking duplicate of  #40

**Closed as completed by nightflyer73** 2018-10-17 07:35 UTC
