### ISSUE TITLE
Check log

### ISSUE THREAD

**Issue by Chiaramonte1981** [nightflyer73/plugin.video.raitv#23] opened 2017-04-15 21:50 UTC
I've tried on 17.1 and 16.1 Kodi. Spmc 16.3 and 16.6. No luck having Rai on demand opening since yesterday. Is the add on dead?

**Comment by nightflyer73** [comment] 2017-04-16 07:43
I have no problem. Please provide a log file.

**Comment by Chiaramonte1981** [comment] 2017-04-16 11:54
How do I get the log.  Everytime I try to open the add on it wont

**Comment by Chiaramonte1981** [comment] 2017-04-16 12:03
Can I email you a screen shot of the log. I can't copy and paste it and email upload fails Everytime

**Comment by Chiaramonte1981** [comment] 2017-04-16 12:19
[
![screenshot_20170416-080136](https://cloud.githubusercontent.com/assets/27584740/25071114/61bd662e-227d-11e7-921a-18b572d65300.png)
](url)

**Comment by Chiaramonte1981** [comment] 2017-04-16 12:22
I added the picture and I added the section of log. Hope this helps

**Comment by nightflyer73** [comment] 2017-04-17 16:08
I'm sorry but that's not enough. I need a complete verbose log file. You can post it to pastebin and link it here.

**Comment by Chiaramonte1981** [comment] 2017-04-17 16:39
https://logs.tvaddons.ag/prcnxqvqj

**Comment by Chiaramonte1981** [comment] 2017-04-17 16:41
I tried it on Kodi Jarvis and Krypton and spmc 16.3 and 16.6 for Android and same issues when opening  https://logs.tvaddons.ag/prcnxqvqj

**Comment by nightflyer73** [comment] 2017-04-17 16:47
This bug is a duplicate of #22.

**Closed by nightflyer73** 2017-04-17 16:47 UTC
